networks:
  fastapi-network:

services:
  backend:
    build: .
    container_name: fastapi-app
    networks:
      - fastapi-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fastapi-network

